ECommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from product.views import *
from .views import *
from .settings import *

def basic(request):
    return render(request, 'basic.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('category/', include('category.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', ProductListView.as_view()),
    path('accounts/register/', Registration.as_view(), name='register'),
    path('product/API/',include('product.api.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

product/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('getbyid/<id>',views.getbyid, name='getbyid'),
    path('deletebyid/<id>',views.deletebyid, name='deletebyid'),
    path('all/',views.getall, name='getall'),
     path('add/',views.add, name='add'),
     path('update/<id>',views.updatebyid, name='updatebyid'),
]

product/urls.py
from django.urls import path
from product.views import *
from django.contrib.auth.decorators import login_required

app_name = 'product'
urlpatterns = [
    path('',login_required(ProductListView.as_view()), name='product'),
    path('<int:pk>/',ProductDetailView.as_view(), name='product_detail'),
    path('Add/', ProductCreateView.as_view(), name='product_add'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
]

# path('', productsList, name='product'),
# path('<int:id>/',productShow,name='productShow'),
# path('Add/',AddProduct,name='AddProduct'),
# path('Delete/<int:id>/',DeleteProduct,name='DeleteProduct'),
# path('Update/<int:id>/',UpdateProduct,name='UpdateProduct'),

product/models.py
from django.db import models
from django.shortcuts import reverse
from category.models import Category

# Create your models here.
class Product(models.Model):
    pname = models.CharField(max_length=100)
    pdetails = models.TextField()
    pimg = models.ImageField(upload_to='product/images', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.pname
    
    @staticmethod
    def get_category_choices():
        return [(category.id, category.cname) for category in Category.objects.all()]

    def __str__(self):
        return  'Name:'+self.name+' email:'+self.email

    @classmethod
    def get_all_products(cls):
        return cls.objects.all()

    @classmethod
    def get_product_by_id(self,id):
        return self.objects.get(id=id)

    def get_trainee_url(self,id):
        return reverse('trainee.details',args=[id])


    def get_trainee_img(self):
        return f'/media/{self.img}'
    

    # category_choices = [(category.id, category.cname) for category in Category.objects.all()]
    # category = models.ForeignKey(Category, on_delete=models.CASCADE, choices=category_choices)

product/api/views.py
from rest_framework.response import Response
from rest_framework import status
from .serializers import ProductSerializer
from product.models import Product
from rest_framework.decorators import api_view

# Show -------------------------------------------------------------
@api_view(['GET'])
def getbyid(request,id):
    productdata=Product.objects.filter(id=id)
    if(len(productdata)>0):
        return Response(data={'data':ProductSerializer(productdata[0]).data},status=200)
    return Response({'msg':'product not found'},status=200)
# Delete ------------------------------------------------------------------
@api_view(['DELETE'])
def deletebyid(request,id):
    productdata=Product.objects.filter(id=id)
    if(len(productdata)>0):
        productdata.delete()
        return Response(data={'msg':'deleted'})
    return Response({'msg':'Product not found'})
# List ---------------------------------------------------------------------
@api_view(['GET'])
def getall(request):
    products=Product.get_all_products()
    selizeddata=[]
    for product in products:
        selizeddata.append(ProductSerializer(product).data)

    return Response({"msg":"done","data":selizeddata})  
# Insert ----------------------------------------------------------------------
@api_view(['POST'])
def add(request):
    product=ProductSerializer(data=request.data)
    if(product.is_valid()):
        product.save()
        return  Response({'msg':'Product added'})
    return Response(product.errors,status=400)
# Update ----------------------------------------------------------------------
@api_view(['GET','PUT'])
def updatebyid(request,id):
    productdata = Product.objects.filter(id=id).first()

    if(productdata):
        serlizeddata=ProductSerializer(instance=productdata,data=request.data)
        if serlizeddata.is_valid():
            serlizeddata.save()
            return Response(data=serlizeddata.data,status=200)
    return Response(serlizeddata.errors,status=400)

product/views.py
# from django.shortcuts import render,reverse
# from django.http import HttpResponseRedirect
# from .models import *
# from .models import Category

# # Create your views here.
# def productsList(request):
#     print(Product.objects.all())
#     context = {'data':Product.objects.all()}
#     return render(request, 'product/product.html', context)
# #------------------------------------------------------------------------------------------------------
# def productShow(request, id):
#     product = Product.objects.get(id=id)
#     context = {'product': product}
#     return render(request, 'product/show.html', context)
# #------------------------------------------------------------------------------------------------------

# # def AddProduct(request):
# #     if(request.method=='POST'):
# #         pname=request.POST['pname']
# #         pdetails=request.POST['pdetails']
# #         pimg = request.FILES['pimg']
# #         Product.objects.create(pname=pname,pdetails=pdetails,pimg=pimg)
# #         return HttpResponseRedirect(reverse('product:product'))
# #     return render(request,'product/insert.html')

# def AddProduct(request):
#     if request.method == 'POST':
#         pname = request.POST['pname']
#         pdetails = request.POST['pdetails']
#         pimg = request.FILES['pimg']
#         category_id = request.POST['category']  
#         category = Category.objects.get(id=category_id)

#         Product.objects.create(pname=pname, pdetails=pdetails, pimg=pimg, category=category)
#         return HttpResponseRedirect(reverse('product:product'))
    
#     categories = Category.objects.all()

#     context = {'categories': categories}
#     return render(request, 'product/insert.html', context)
# # ------------------------------------------------------------------------------------------------------------
# def DeleteProduct(request,id):
#     Product.objects.filter(id=id).delete()
#     return HttpResponseRedirect(reverse('product:product'))

# def UpdateProduct(request,id):
#     context={}
#     if(request.method=='POST'):
#         print(request.POST)
#         Product.objects.filter(id=id).update(
#             pname=request.POST['pname'],
#             pdetails=request.POST['pdetails'],
#             pimg=request.POST['pimg'],
#         )
#         return HttpResponseRedirect(reverse('category:category'))
#     product=Product.objects.get(id=id)
#     context['product']=product
#     return render(request,'product/update.html',context)
# #------------------------------------------------------------------------------------------------------
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Product
from .models import Category
from django.contrib.auth.decorators import login_required

class ProductListView(ListView):
    model = Product
    template_name = 'product/product.html'
    context_object_name = 'data'

#------------------------------------------------------------------------------------------------------

class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/show.html'
    context_object_name = 'product' 

#------------------------------------------------------------------------------------------------------

class ProductCreateView(CreateView):
    model = Product
    template_name = 'product/insert.html'
    fields = ['pname', 'pdetails', 'pimg', 'category']

    def form_valid(self, form):
        category_id = self.request.POST.get('category')
        category = Category.objects.get(id=category_id)
        form.instance.category = category
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all() 
        return context
    
    def get_success_url(self):
        return reverse_lazy('product:product')
    
#------------------------------------------------------------------------------------------------------

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product/delete.html'
    success_url = reverse_lazy('product:product') 

#------------------------------------------------------------------------------------------------------

class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'product/update.html'
    fields = ['pname', 'pdetails', 'pimg', 'category']
    success_url = reverse_lazy('product:product') 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        print("Form is valid. Updating product...")
        if form.is_valid():
            print("Form is valid. Saving form data...")
            form.save()
        else:
            print("Form is not valid. Errors:", form.errors)
        return super().form_valid(form)

templates/product/delete.html
{% extends 'basic.html' %}

{% block title %}
    Delete Product
{% endblock %}

{% block delete %}
<div class="container mt-5 mb-5">
    <h1>Delete Product</h1>
    <div class="row">
        <div class="col-6">
        <div class="card p-3 w-75">
            <p>Are you sure you want to delete this product?</p>
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Delete" class="btn btn-danger w-100">
            </form>
            <br>
            <a href="{% url 'product:product' %}" class="btn btn-info">Cancel</a>
</div>
</div>
</div>
</div>
{% endblock %}

templates/product/insert.html
{%extends 'basic.html'%}
{%block title%}
    Product - Add
{%endblock%}
{%block insert%}
<div class="container mt-5 mb-5">
    <h1>Insert Product</h1>
    <div class="row">
        <div class="col-6">
        <div class="card p-3 w-75">
          <form method="post" enctype="multipart/form-data">
                {%csrf_token%}
                  <label>Name:</label>
                <input type="text" name="pname" required class="form-control"></br>
          
                  <label>Details:</label>
                <input type="text" name="pdetails" required class="form-control"></br>
          
                  <label>Image:</label>
                <input type="file" name="pimg" required class="form-control"></br>

                <label>Category:</label>
                <select name="category" class="form-control" required>
                    {% for category in categories %}
                        <option value="{{ category.id }}" class="text-dark">{{ category.cname }}</option>
                    {% endfor %}
                </select><br>

                <input type="submit" value="Add Product" class="form-control btn btn-warning">
            </form>
            &nbsp;
    <button onclick="history.back()" class="btn btn-danger form-control">Back</button>
</div>
</div>
</div>
</div>
{%endblock%}

templates/product/product.html
{% extends 'basic.html' %}
{% load static %}
{% block title %}Product - List{% endblock %}

{% block product %}
<h1>Product Page</h1>
<form action="{% url 'product:product_add' %}" method="get">
<button class="btn btn-danger" type="submit">Insert Product</button>
</form>
<table class="table">
    <thead>
    <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Details</td>
        <td>Category</td>
        <td>Images</td>
        <td>Actions</td>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    {%for product in data%}
         <tr>
            <td>{{product.id}}</td>
            <td>{{product.pname}}</td>
            <td>{{product.pdetails}}</td>
            <td>{{ product.category.cname }}</td>
            <td><img src="{{ product.pimg.url }}"/></td>
            <td>
                <form action="{% url 'product:product_detail' pk=product.id %}" >
                    <button type="submit" class="btn btn-warning">Show</button>
                </form>
                &nbsp;
                <form action="{% url 'product:product_update' pk=product.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Update</button>
                </form>
                &nbsp;
                <form action="{% url 'product:product_delete' pk=product.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Delete</button>
                </form>
                
            </td>
        </tr>
    {%endfor%}
    </tbody>
</table>
{% endblock %}

templates/product/show.html
{% extends 'basic.html' %} 
{% load static%}
{% block title %} Product Details {% endblock %} 
{% block show %} 
<div class="container mt-5 mb-5">
    <h1>Product Details</h1>
    <div class="row">
        <div class="col-6">
        <div class="card p-3 w-75">
    <img src="{{ product.pimg.url }}" class="w-75"/>
    <hr class="text-danger">
    <p><span class="fw-bold fs-5">Name: </span> {{ product.pname }}</p>
    <p><span class="fw-bold fs-5">Details: </span> {{ product.pdetails }}</p>
    <button onclick="history.back()" class="btn btn-danger">Back</button>
</div>
</div>
</div>
</div>
{% endblock %}

templates/product/update.html
{%extends 'basic.html'%}
{%block title%}
    Product - Update
{%endblock%}
{%block update%}
<div class="container mt-5 mb-5">
    <h1>Update Product</h1>
    <div class="row">
        <div class="col-6">
        <div class="card p-3 w-75">
            <form method="post">
                {%csrf_token%}
                  <label>Name:</label>
                <input type="text" name="pname" required class="form-control" value="{{product.pname}}" ></br>
          
                  <label>Details:</label>
                <input type="text" name="pdetails" required class="form-control" value="{{product.pdetails}}"></br>
          
                  <label>Image:</label>
                <input type="file" name="pimg" required class="form-control"></br>
                <label>Category:</label>
                <select name="category" class="form-control" required>
                    {% for category in categories %}
                        <option value="{{ category.id }}" class="text-dark">{{ category.cname }}</option>
                    {% endfor %}
                </select><br>
                <input type="submit" value="Update Product" class="form-control btn btn-warning">
            </form>
            &nbsp;
    <button onclick="history.back()" class="btn btn-danger form-control">Back</button>
</div>
</div>
</div>
</div>
{%endblock%}